apiVersion: apps/v1
kind: Deployment
metadata:
  name: web-client
spec:
  replicas: 1
  selector:
    matchLabels:
      app: web-client
  template:
    metadata:
      labels:
        app: web-client
    spec:
      containers:
        - name: web-client
          image: robson93/jetwise.web-client:latest
          ports:
            - containerPort: 8080
          imagePullPolicy: IfNotPresent
---
apiVersion: v1
kind: Service
metadata:
  name: web-client
spec:
  selector:
    app: web-client
  ports:
    - protocol: TCP
      port: 80          # zostaje jako zewnętrzny port (może być 80)
      targetPort: 8080  # musi wskazywać na port aplikacji w kontenerze!
      nodePort: 32306   # tylko jeśli potrzebujesz konkretnego NodePort
  type: NodePort