name: Build & Deploy

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: self-hosted

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up .NET SDK
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: "8.0.x"

      - name: Restore dependencies
        run: dotnet restore ./src/services/Jetwise.Services.Booking/Jetwise.Services.Booking/Jetwise.Services.Booking.csproj

      - name: Build the solution
        run: dotnet build ./src/services/Jetwise.Services.Booking/Jetwise.Services.Booking/Jetwise.Services.Booking.csproj --configuration Release

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build Docker image
        run: docker build -t ${{ secrets.DOCKER_USERNAME }}/jetwise.services.booking:${{ github.sha }} ./src/services/Jetwise.Services.Booking

      - name: Push Docker image
        run: docker push ${{ secrets.DOCKER_USERNAME }}/jetwise.services.booking:${{ github.sha }}

      - name: Replace image tag in manifest
        run: |
          sed -i "s|image: .*|image: ${{ secrets.DOCKER_USERNAME }}/jetwise.services.booking:${{ github.sha }}|" deploy/k8s.yaml

      - name: Deploy to k3s
        run: kubectl apply -f deploy/k8s.yaml
        env:
          KUBECONFIG: /etc/rancher/k3s/k3s.yaml